name: run-test-suite
on:
  push:
    branches: [ master, 4-3-stable, 5-1-stable ]
  pull_request:
    branches: [ master, 4-3-stable, 5-1-stable ]

jobs:
  test:
    services:
      # https://github.com/docker-library/docs/blob/master/postgres/README.md
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ancestry_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
          image: mysql:8.0
          env:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: ancestry_test
          ports:
            - "3306:3306"
          options: >-
            --health-cmd="mysqladmin ping"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=3
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # this matrix is driven by these sources:
        # - https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html
        # - https://guides.rubyonrails.org/maintenance_policy.html
        include:
          # EOL 2023
          - format: materialized_path2
            activerecord: 60
            ruby: 2.7
          - format: materialized_path2
            activerecord: 61
            ruby: "3.0"
          - format: materialized_path2
            activerecord: 70
            ruby: "3.0"
          - format: materialized_path2
            activerecord: 71
            ruby: "3.0"
          # --- Stable ---
          - activerecord: 72
            format: materialized_path2
            ruby: "3.2"
          - activerecord: 72
            format: materialized_path
            ruby: "3.3"
            mysql: true
          - activerecord: 81
            format: materialized_path2
            ruby: "3.4"
          - activerecord: 81
            format: ltree
            ruby: "3.4"
          - activerecord: 81
            format: materialized_path
            ruby: "4.0" # Latest Ruby
          - activerecord: 81
            format: materialized_path3
            ruby: "3.4"
          - activerecord: 81
            format: array
            ruby: "3.4"

    env:
      # for the pg cli (psql, pg_isready) and possibly rails
      PGHOST: 127.0.0.1 # container is mapping it locally
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: password
      # for the mysql cli (mysql, mysqladmin)
      MYSQL_HOST: 127.0.0.1
      MYSQL_PWD: password
      # for rails tests (from matrix)
      BUNDLE_GEMFILE: gemfiles/gemfile_${{ matrix.activerecord }}.gemfile
      FORMAT: ${{ matrix.format }}
      ANCESTRY_COLUMN: ancestry_alt
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: setup Ruby
        # https://github.com/ruby/setup-ruby#versioning
        # runs 'bundle install' and caches installed gems automatically
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: run sqlite tests
        if: matrix.format != 'ltree' && matrix.format != 'array'
        env:
          DB: sqlite3
        run: |
          bundle exec rake
      - name: run sqlite tests (UPDATE_STRATEGY=sql)
        if: matrix.format != 'ltree' && matrix.format != 'array'
        env:
          DB: sqlite3
          UPDATE_STRATEGY: sql
        run: |
          bundle exec rake
      - name: run pg tests
        env:
          DB: pg
        run: |
          bundle exec rake
      - name: run pg tests (UPDATE_STRATEGY=sql)
        env:
          DB: pg
          UPDATE_STRATEGY: sql
        run: |
          bundle exec rake
      - name: run mysql tests
        if: matrix.mysql
        env:
          DB: mysql2
        run: |
          bundle exec rake
      - name: run mysql tests (UPDATE_STRATEGY=sql)
        if: matrix.mysql
        env:
          DB: mysql2
          UPDATE_STRATEGY: sql
        run: |
          bundle exec rake
      - name: run mysql tests (ANCESTRY_COLUMN_TYPE=binary)
        if: matrix.mysql
        env:
          DB: mysql2
          ANCESTRY_COLUMN_TYPE: binary
        run: |
          bundle exec rake
