graph TD
A((A)) --- B((B))
A --- C((C))
A --- D((D))
B --- E((E))
C --- F((F))
C --- G((G))

classDef reference stroke:#134,stroke-width:10px
classDef selected fill:#fd7

class A reference
class B,C,D,E,F,G selected
